In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from itertools import combinations, groupby, chain
from collections import Counter

In [2]:
cluster0_item_rules = pd.read_csv('data/group0_item_rules.csv', index_col = 0)
cluster1_item_rules = pd.read_csv('data/group1_item_rules.csv', index_col = 0)
cluster2_item_rules = pd.read_csv('data/group2_item_rules.csv', index_col = 0)
cluster3_item_rules = pd.read_csv('data/group3_item_rules.csv', index_col = 0)
cluster4_item_rules = pd.read_csv('data/group4_item_rules.csv', index_col = 0)
cluster5_item_rules = pd.read_csv('data/group5_item_rules.csv', index_col = 0)
cluster0_aisle_rules = pd.read_csv('data/group0_aisle_rules.csv', index_col = 0)
cluster1_aisle_rules = pd.read_csv('data/group1_aisle_rules.csv', index_col = 0)
cluster2_aisle_rules = pd.read_csv('data/group2_aisle_rules.csv', index_col = 0)
cluster3_aisle_rules = pd.read_csv('data/group3_aisle_rules.csv', index_col = 0)
cluster4_aisle_rules = pd.read_csv('data/group4_aisle_rules.csv', index_col = 0)
cluster5_aisle_rules = pd.read_csv('data/group5_aisle_rules.csv', index_col = 0)

In [3]:
products = pd.read_csv('data/products.csv', index_col = 0)
aisles = pd.read_csv('data/aisles.csv', index_col = 0)
clusters = pd.read_csv('data/cluster_df.csv', index_col = 0)

In [4]:
cluster_df = clusters.set_index('user_id')
cluster_df

                0         1         2         3         4         5  cluster
user_id
1       -0.103161  0.048617 -0.031835 -0.005633 -0.053023 -0.055260        2
2       -0.077766  0.077983 -0.076149 -0.101672  0.081782 -0.040408        2
3        0.057496  0.085719  0.001778 -0.013190 -0.028493  0.113080        1
4       -0.055343  0.134731 -0.002393 -0.037707 -0.087805 -0.027371        4
5        0.133937 -0.019591 -0.020960 -0.003733  0.057735  0.138888        1
...           ...       ...       ...       ...       ...       ...      ...
206205  -0.021674  0.081783 -0.073478 -0.088435  0.155957 -0.022705        1
206206  -0.040315 -0.036658 -0.024050  0.010052 -0.051020  0.000829        2
206207  -0.022110 -0.032613 -0.009467 -0.015798  0.021497  0.020466        1
206208  -0.002217 -0.010633 -0.037620 -0.007753  0.028732  0.044835        1
206209  -0.072488  0.017515 -0.043591 -0.003228 -0.010484  0.027625        2

[206209 rows x 7 columns]

In [5]:
cluster_item_rules_dic = {}
cluster_item_rules_dic[0] = cluster0_item_rules
cluster_item_rules_dic[1] = cluster1_item_rules
cluster_item_rules_dic[2] = cluster2_item_rules
cluster_item_rules_dic[3] = cluster3_item_rules
cluster_item_rules_dic[4] = cluster4_item_rules
cluster_item_rules_dic[5] = cluster5_item_rules

In [6]:
 cluster_item_rules_dic[4]

,item_A,item_B,product_name_A,product_name_B,freqAB,supportAB,freqA,supportA,freqB,supportB,confidenceAtoB,confidenceBtoA,lift
0,4985,36278,Homestyle Some Pulp Orange Juice,Chocolate Breakfast Biscuits Chocolate,27,0.000127,30,0.000141,28,0.000132,0.900000,0.964286,6831.610714
1,4985,48927,Homestyle Some Pulp Orange Juice,Fat Free Plain Yoghurt,24,0.000113,30,0.000141,55,0.000259,0.800000,0.436364,3091.476364
2,36278,48927,Chocolate Breakfast Biscuits Chocolate,Fat Free Plain Yoghurt,25,0.000118,28,0.000132,55,0.000259,0.892857,0.454545,3450.308442
3,24852,48927,Banana,Fat Free Plain Yoghurt,29,0.000136,47828,0.225032,55,0.000259,0.000606,0.527273,2.343105
4,38259,38576,Blueberry Greek Yogurt + Chia,The Epic Seed Greek Yogurt Strawberry & Chia,23,0.000108,31,0.000146,25,0.000118,0.741935,0.920000,6307.609032
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43737,21137,49174,Organic Strawberries,Raincoast Crisps Cranberry And Hazelnut Crackers,27,0.000127,29393,0.138295,98,0.000461,0.000919,0.275510,1.992198
43738,21137,25715,Organic Strawberries,Organic Green Grapes,25,0.000118,29393,0.138295,94,0.000442,0.000851,0.265957,1.923122
43739,21137,45374,Organic Strawberries,Newman O's Creme Filled Chocolate Cookies,23,0.000108,29393,0.138295,93,0.000438,0.000782,0.247312,1.788297
43740,21137,22950,Organic Strawberries,Natural Free & Clear Dishwasher Detergent Packs,29,0.000136,29393,0.138295,138,0.000649,0.000987,0.210145,1.519545
43741,21137,21955,Organic Strawberries,All Natural Marinara Pasta Sauce,23,0.000108,29393,0.138295,117,0.000550,0.000782,0.196581,1.421467

In [7]:
cluster_aisle_rules_dic = {}
cluster_aisle_rules_dic[0] = cluster0_aisle_rules
cluster_aisle_rules_dic[1] = cluster1_aisle_rules
cluster_aisle_rules_dic[2] = cluster2_aisle_rules
cluster_aisle_rules_dic[3] = cluster3_aisle_rules
cluster_aisle_rules_dic[4] = cluster4_aisle_rules
cluster_aisle_rules_dic[5] = cluster5_aisle_rules

In [8]:
cluster_aisle_rules_dic[4]

,aisle_A,aisle_B,aisle_name_A,aisle_name_B,freqAB,supportAB,freqA,supportA,freqB,supportB,confidenceAtoB,confidenceBtoA,lift
0,28,62,red wines,white wines,131,0.000633,354,0.001709,325,0.001569,0.370056,0.403077,235.790891
1,27,62,beers coolers,white wines,81,0.000391,685,0.003308,325,0.001569,0.118248,0.249231,75.344827
2,32,62,packaged produce,white wines,28,0.000135,24648,0.119025,325,0.001569,0.001136,0.086154,0.723828
3,21,62,packaged cheese,white wines,24,0.000116,28470,0.137482,325,0.001569,0.000843,0.073846,0.537134
4,31,62,refrigerated,white wines,26,0.000126,20663,0.099782,325,0.001569,0.001258,0.080000,0.801750
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5301,84,132,milk,beauty,29,0.000140,50371,0.243242,136,0.000657,0.000576,0.213235,0.876639
5302,91,132,soy lactosefree,beauty,26,0.000126,31966,0.154364,136,0.000657,0.000813,0.191176,1.238479
5303,120,132,yogurt,beauty,28,0.000135,48642,0.234892,136,0.000657,0.000576,0.205882,0.876496
5304,123,132,packaged vegetables fruits,beauty,53,0.000256,75240,0.363334,136,0.000657,0.000704,0.389706,1.072582
5305,24,132,fresh fruits,beauty,110,0.000531,171605,0.828681,136,0.000657,0.000641,0.808824,0.976037

In [9]:
# returns top x items associated based on lift

def product(cluster, product_id, item_lift, product_name, num_products):
    df = cluster_item_rules_dic[cluster]
    df = df[(df['item_A'] == product_id) | (df['item_B'] == product_id)][['product_name_A','item_A','product_name_B','item_B','confidenceAtoB','lift']].sort_values('lift', ascending = False)
    df = df[df['lift'] > item_lift]
    df = df.sort_values('lift', ascending = False)
    df = df.head(n = num_products)
    product_associations = df['product_name_A'].values.tolist()
    for x in df['product_name_B'].values.tolist():
        product_associations.append(x)
    product_associations = [x for x in product_associations if x != product_name]
    return product_associations

In [10]:
# returns recommended products given inputs

def prod_recommender(user_id, product_id, item_lift, num_products):
    
    product_name = products.at[product_id,'product_name']
    aisle_id = products.at[product_id,'aisle_id']
    aisle_name = aisles.at[aisle_id,'aisle']
    cluster = cluster_df.at[user_id, 'cluster']
    print(cluster)
    return product(cluster = cluster, product_id = product_id, item_lift = item_lift, 
                              product_name = product_name, num_products = num_products)

In [11]:
user__id = int(input("Enter user id "))
num__products = int(input("Enter Number of recommendations "))
product_id = 39055
item_lift = 1

Enter user id 5
Enter Number of recommendations 10

In [12]:
prod_recommender(user__id, product_id, item_lift, num__products)

1

['Thin & Light Tortilla Chips',
 'Organic Large Brown Grade AA Cage Free Eggs',
 'Organic Reduced Fat 2% Milk',
 'Organic Large Grade AA Brown Eggs',
 'Original Hummus',
 'Uncured Genoa Salami',
 'Red Peppers',
 'Organic Black Beans',
 'Thick & Crispy Tortilla Chips',
 'Organic Sour Cream']

In [13]:
import pickle

In [14]:
pickle.dump(prod_recommender, open('model.pkl','wb'))